#ifndef  __DATASAVEI2C_H__
#define  __DATASAVEI2C_H__

#define UN_VALID_DATA 		0xEE

#define DATA_VALID_FLAG_OFFSET    0x04
#define DATA_VALID_FLAG           0xE1E2E3E4

/**************系统设置密码存储地址*********************/
#define SYS_CFG_LICENSE_SAVE_OFFSET  	(DATA_VALID_FLAG_OFFSET + 5)
#define SYS_CFG_LICENSE_SAVE_NUM		6

/**************出厂设置密码存储地址*********************/
#define FACTORY_SET_LICENSE_SAVE_OFFSET  	(SYS_CFG_LICENSE_SAVE_OFFSET + SYS_CFG_LICENSE_SAVE_NUM)
#define FACTORY_SET_LICENSE_SAVE_NUM		6

/**************系统配置段存储地址*********************/
#define SYS_CFG_SAVE_OFFSET  	(FACTORY_SET_LICENSE_SAVE_OFFSET + FACTORY_SET_LICENSE_SAVE_NUM)
#define SYS_CFG_SAVE_NUM		96

/****************************系统浮充电流存储地址***********************************/
#define FLOAT_CURRENT_PARA_OFFSET  	(SYS_CFG_SAVE_OFFSET + SYS_CFG_SAVE_NUM)
#define FLOAT_CURRENT_PARA_NUM		4

/**************通讯参数段存储地址*********************/
#define COM_PARA_SAVE_OFFSET		(FLOAT_CURRENT_PARA_OFFSET+FLOAT_CURRENT_PARA_NUM)
#define COM_PARA_SAVE_NUM			100

/****************************段内通讯参数存储地址***********************************/
#define CAN_PARA_SAVE_OFFSET		(FLOAT_CURRENT_PARA_OFFSET+FLOAT_CURRENT_PARA_NUM)
#define CAN_PARA_SAVE_NUM			12


#define COM1_PARA_SAVE_OFFSET		(CAN_PARA_SAVE_OFFSET+CAN_PARA_SAVE_NUM)
#define COM1_PARA_SAVE_NUM			12


#define COM2_PARA_SAVE_OFFSET		(COM1_PARA_SAVE_OFFSET+COM1_PARA_SAVE_NUM)
#define COM2_PARA_SAVE_NUM			12


#define COM3_PARA_SAVE_OFFSET		(COM2_PARA_SAVE_OFFSET+COM2_PARA_SAVE_NUM)
#define COM3_PARA_SAVE_NUM			12


#define COM4_PARA_SAVE_OFFSET		(COM3_PARA_SAVE_OFFSET+COM3_PARA_SAVE_NUM)
#define COM4_PARA_SAVE_NUM			12
/*******************通信参数段内实际使用空间***************************/
#define COM_PARA_DATA_NUM	0x04	//一个通信端口内使用的寄存器数量，在铁电里面存储的寄存器数量
/**************内阻历史测量信息存储地址*********************/
#define HIS1_MEA_SAVE_OFFSET		(COM_PARA_SAVE_OFFSET+COM_PARA_SAVE_NUM)
#define HIS1_MEA_SAVE_NUM			20000	//10组内阻测量信息，每组信息包括测量时间，内阻，连接条，电池电压，温度数据


/*******************************段内每一个数据区域的长度***********************/
#define HIS_MEA_INNER_R_DATA_OFFSET_NUM		20		//
#define HIS_MEA_CR_DATA_OFFSET_NUM		500		//
#define HIS_MEA_VOLTAGE_DATA_OFFSET_NUM			980		//
#define HIS_MEA_TEMP_DATA_OFFSET_NUM		1460		//

/**************内阻历史测量信息每一次的起始存储地址*********************/
#define LAST_TEST_SAVE_ADDR_FLAG1_OFFSET	(COM_PARA_SAVE_OFFSET+COM_PARA_SAVE_NUM)//存储最近一次内阻测量存储位置
#define LAST_TEST_ADDR_FLAG1_NUM		1

#define TOTAL_TEST_TIMES_BAT1_OFFSET	(LAST_TEST_SAVE_ADDR_FLAG1_OFFSET+LAST_TEST_ADDR_FLAG1_NUM)//总测量次数存储位置
#define TOTAL_TEST_TIMES_BAT1_NUM		1

#define HIS1_MEA_TIME1_SAVE_OFFSET	(TOTAL_TEST_TIMES_BAT1_OFFSET+TOTAL_TEST_TIMES_BAT1_NUM)
#define HIS1_MEA_TIME1_NUM		2000	//	1组内阻信息


#define HIS1_MEA_TIME2_SAVE_OFFSET	(HIS1_MEA_TIME1_SAVE_OFFSET+HIS1_MEA_TIME1_NUM)
#define HIS1_MEA_TIME2_NUM		2000


#define HIS1_MEA_TIME3_SAVE_OFFSET	(HIS1_MEA_TIME2_SAVE_OFFSET+HIS1_MEA_TIME2_NUM)
#define HIS1_MEA_TIME3_NUM		2000


#define HIS1_MEA_TIME4_SAVE_OFFSET	(HIS1_MEA_TIME3_SAVE_OFFSET+HIS1_MEA_TIME3_NUM)
#define HIS1_MEA_TIME4_NUM		2000


#define HIS1_MEA_TIME5_SAVE_OFFSET	(HIS1_MEA_TIME4_SAVE_OFFSET+HIS1_MEA_TIME4_NUM)
#define HIS1_MEA_TIME5_NUM		2000

#define HIS1_MEA_TIME6_SAVE_OFFSET	(HIS1_MEA_TIME5_SAVE_OFFSET+HIS1_MEA_TIME5_NUM)
#define HIS1_MEA_TIME6_NUM		2000

#define HIS1_MEA_TIME7_SAVE_OFFSET	(HIS1_MEA_TIME6_SAVE_OFFSET+HIS1_MEA_TIME6_NUM)
#define HIS1_MEA_TIME7_NUM		2000

#define HIS1_MEA_TIME8_SAVE_OFFSET	(HIS1_MEA_TIME7_SAVE_OFFSET+HIS1_MEA_TIME7_NUM)
#define HIS1_MEA_TIME8_NUM		2000

#define HIS1_MEA_TIME9_SAVE_OFFSET	(HIS1_MEA_TIME8_SAVE_OFFSET+HIS1_MEA_TIME8_NUM)
#define HIS1_MEA_TIME9_NUM		2000

#define HIS1_MEA_TIME10_SAVE_OFFSET	(HIS1_MEA_TIME9_SAVE_OFFSET+HIS1_MEA_TIME9_NUM)
#define HIS1_MEA_TIME10_NUM		2000


/********************************************************************************************/
#define HIS2_MEA_SAVE_OFFSET		(HIS1_MEA_SAVE_OFFSET+HIS1_MEA_SAVE_NUM)
#define HIS2_MEA_SAVE_NUM			20000

/**************内阻历史测量信息每一次的起始存储地址*********************/
#define LAST_TEST_SAVE_ADDR_FLAG2_OFFSET	HIS2_MEA_SAVE_OFFSET//存储最近一次内阻测量存储位置
#define LAST_TEST_ADDR_FLAG2_NUM		1

#define TOTAL_TEST_TIMES_BAT2_OFFSET	(LAST_TEST_SAVE_ADDR_FLAG2_OFFSET+LAST_TEST_ADDR_FLAG2_NUM)//总测量次数存储位置
#define TOTAL_TEST_TIMES_BAT2_NUM		1

#define HIS2_MEA_TIME1_SAVE_OFFSET	(TOTAL_TEST_TIMES_BAT2_OFFSET+TOTAL_TEST_TIMES_BAT2_NUM)
#define HIS2_MEA_TIME1_NUM		2000


#define HIS2_MEA_TIME2_SAVE_OFFSET	(HIS2_MEA_TIME1_SAVE_OFFSET+HIS2_MEA_TIME1_NUM)
#define HIS2_MEA_TIME2_NUM		2000


#define HIS2_MEA_TIME3_SAVE_OFFSET	(HIS2_MEA_TIME2_SAVE_OFFSET+HIS2_MEA_TIME2_NUM)
#define HIS2_MEA_TIME3_NUM		2000


#define HIS2_MEA_TIME4_SAVE_OFFSET	(HIS2_MEA_TIME3_SAVE_OFFSET+HIS2_MEA_TIME3_NUM)
#define HIS2_MEA_TIME4_NUM		2000


#define HIS2_MEA_TIME5_SAVE_OFFSET	(HIS2_MEA_TIME4_SAVE_OFFSET+HIS2_MEA_TIME4_NUM)
#define HIS2_MEA_TIME5_NUM		2000

#define HIS2_MEA_TIME6_SAVE_OFFSET	(HIS2_MEA_TIME5_SAVE_OFFSET+HIS2_MEA_TIME5_NUM)
#define HIS2_MEA_TIME6_NUM		2000

#define HIS2_MEA_TIME7_SAVE_OFFSET	(HIS2_MEA_TIME6_SAVE_OFFSET+HIS2_MEA_TIME6_NUM)
#define HIS2_MEA_TIME7_NUM		2000

#define HIS2_MEA_TIME8_SAVE_OFFSET	(HIS2_MEA_TIME7_SAVE_OFFSET+HIS2_MEA_TIME7_NUM)
#define HIS2_MEA_TIME8_NUM		2000

#define HIS2_MEA_TIME9_SAVE_OFFSET	(HIS2_MEA_TIME8_SAVE_OFFSET+HIS2_MEA_TIME8_NUM)
#define HIS2_MEA_TIME9_NUM		2000

#define HIS2_MEA_TIME10_SAVE_OFFSET	(HIS2_MEA_TIME9_SAVE_OFFSET+HIS2_MEA_TIME9_NUM)
#define HIS2_MEA_TIME10_NUM		2000


/********************************************************************************************/

/**************历史记录段存储地址*********************/
#define HISTORY1_RECORD_SAVE_OFFSET	(HIS2_MEA_SAVE_OFFSET+HIS2_MEA_SAVE_NUM)	//蓄电池组1的历史记录存储地址
#define HISTORY1_RECORD_SAVE_NUM		9000

#define HISTORY1_RECORD_QUANTITY_OFFSET	HISTORY1_RECORD_SAVE_OFFSET
#define HISTORY1_RECORD_QUANTITY_NUM	2

#define QUANTITY1_OVER_MAX_NUM_OFFSET	(HISTORY1_RECORD_QUANTITY_OFFSET+HISTORY1_RECORD_QUANTITY_NUM)
#define QUANTITY1_FLAG_NUM	1

#define HISTORY1_RECORD_NO1_OFFSET	(QUANTITY1_OVER_MAX_NUM_OFFSET + QUANTITY1_FLAG_NUM)
#define HISTORY1_RECORD_NO1_NUM			16

#define HISTORY2_RECORD_SAVE_OFFSET	(HISTORY1_RECORD_SAVE_OFFSET+HISTORY1_RECORD_SAVE_NUM)	//蓄电池组2的历史记录存储地址
#define HISTORY2_RECORD_SAVE_NUM		9000

#define HISTORY2_RECORD_QUANTITY_OFFSET	HISTORY2_RECORD_SAVE_OFFSET
#define HISTORY2_RECORD_QUANTITY_NUM		2

#define QUANTITY2_OVER_MAX_NUM_OFFSET	(HISTORY2_RECORD_QUANTITY_OFFSET+HISTORY2_RECORD_QUANTITY_NUM)
#define QUANTITY2_FLAG_NUM	1

#define HISTORY2_RECORD_NO1_OFFSET	(QUANTITY2_OVER_MAX_NUM_OFFSET + QUANTITY2_FLAG_NUM)
#define HISTORY2_RECORD_NO1_NUM			16	

/******************************************备份数据段存储地址*************************************************/

#define BKP_DATA_SAVE_OFFSET		(HISTORY2_RECORD_SAVE_OFFSET + HISTORY2_RECORD_SAVE_NUM)
#define BKP_UN_VALID_DATA 		0xEE

#define BKP_DATA_VALID_FLAG_OFFSET    (BKP_DATA_SAVE_OFFSET+4)


/**************系统设置密码存储地址*********************/
#define BKP_SYS_CFG_LICENSE_SAVE_OFFSET  	(BKP_DATA_VALID_FLAG_OFFSET + 5)

/**************出厂设置密码存储地址*********************/
#define BKP_FACTORY_SET_LICENSE_SAVE_OFFSET  	(BKP_SYS_CFG_LICENSE_SAVE_OFFSET + SYS_CFG_LICENSE_SAVE_NUM)

/****************************系统配置段存储地址***********************************/
#define BKP_SYS_CFG_SAVE_OFFSET  	(BKP_FACTORY_SET_LICENSE_SAVE_OFFSET+FACTORY_SET_LICENSE_SAVE_NUM)

/****************************系统浮充电流存储地址***********************************/
#define BKP_FLOAT_CURRENT_PARA_OFFSET  	(BKP_SYS_CFG_SAVE_OFFSET + SYS_CFG_SAVE_NUM)

/****************************通讯参数段存储地址***********************************/
#define BKP_COM_PARA_SAVE_OFFSET		(BKP_FLOAT_CURRENT_PARA_OFFSET+FLOAT_CURRENT_PARA_NUM)
/********************************************段内通讯参数存储地址***************************************************/
#define BKP_CAN_PARA_SAVE_OFFSET			(BKP_FLOAT_CURRENT_PARA_OFFSET+FLOAT_CURRENT_PARA_NUM)
#define BKP_COM1_PARA_SAVE_OFFSET		(BKP_CAN_PARA_SAVE_OFFSET+CAN_PARA_SAVE_NUM)
#define BKP_COM2_PARA_SAVE_OFFSET		(BKP_COM1_PARA_SAVE_OFFSET+COM1_PARA_SAVE_NUM)
#define BKP_COM3_PARA_SAVE_OFFSET		(BKP_COM2_PARA_SAVE_OFFSET+COM2_PARA_SAVE_NUM)
#define BKP_COM4_PARA_SAVE_OFFSET		(BKP_COM3_PARA_SAVE_OFFSET+COM3_PARA_SAVE_NUM)

/************************************站信息存储地址*******************************************/
#define STATION_INFO_SAVE_OFFSET	(BKP_COM4_PARA_SAVE_OFFSET+COM4_PARA_SAVE_NUM)
#define STATION_INFO_SAVE_NUM	200

/***********************************1组蓄电池测试时运行状态信息地址********************************************/
#define BAT_GROUP_STAT_INFO_OFFSET	(STATION_INFO_SAVE_OFFSET+STATION_INFO_SAVE_NUM)

#define BAT1_GROUP_STAT_INFO1_OFFSET	(STATION_INFO_SAVE_OFFSET+STATION_INFO_SAVE_NUM)
#define BAT1_GROUP_STAT_INFO1_NUM		60

#define BAT1_GROUP_STAT_INFO2_OFFSET	(BAT1_GROUP_STAT_INFO1_OFFSET+BAT1_GROUP_STAT_INFO1_NUM)
#define BAT1_GROUP_STAT_INFO2_NUM		60

#define BAT1_GROUP_STAT_INFO3_OFFSET	(BAT1_GROUP_STAT_INFO2_OFFSET+BAT1_GROUP_STAT_INFO1_NUM)
#define BAT1_GROUP_STAT_INFO3_NUM		60

#define BAT1_GROUP_STAT_INFO4_OFFSET	(BAT1_GROUP_STAT_INFO3_OFFSET+BAT1_GROUP_STAT_INFO1_NUM)
#define BAT1_GROUP_STAT_INFO4_NUM		60

#define BAT1_GROUP_STAT_INFO5_OFFSET	(BAT1_GROUP_STAT_INFO4_OFFSET+BAT1_GROUP_STAT_INFO1_NUM)
#define BAT1_GROUP_STAT_INFO5_NUM		60

#define BAT1_GROUP_STAT_INFO6_OFFSET	(BAT1_GROUP_STAT_INFO5_OFFSET+BAT1_GROUP_STAT_INFO1_NUM)
#define BAT1_GROUP_STAT_INFO6_NUM		60

#define BAT1_GROUP_STAT_INFO7_OFFSET	(BAT1_GROUP_STAT_INFO6_OFFSET+BAT1_GROUP_STAT_INFO1_NUM)
#define BAT1_GROUP_STAT_INFO7_NUM		60

#define BAT1_GROUP_STAT_INFO8_OFFSET	(BAT1_GROUP_STAT_INFO7_OFFSET+BAT1_GROUP_STAT_INFO1_NUM)
#define BAT1_GROUP_STAT_INFO8_NUM		60

#define BAT1_GROUP_STAT_INFO9_OFFSET	(BAT1_GROUP_STAT_INFO8_OFFSET+BAT1_GROUP_STAT_INFO1_NUM)
#define BAT1_GROUP_STAT_INFO9_NUM		60

#define BAT1_GROUP_STAT_INFO10_OFFSET	(BAT1_GROUP_STAT_INFO9_OFFSET+BAT1_GROUP_STAT_INFO1_NUM)
#define BAT1_GROUP_STAT_INFO10_NUM		60

/***********************************2组蓄电池测试时运行状态信息地址********************************************/
#define BAT2_GROUP_STAT_INFO1_OFFSET	(BAT1_GROUP_STAT_INFO10_OFFSET+BAT1_GROUP_STAT_INFO10_NUM)
#define BAT2_GROUP_STAT_INFO1_NUM		60

#define BAT2_GROUP_STAT_INFO2_OFFSET	(BAT2_GROUP_STAT_INFO1_OFFSET+BAT2_GROUP_STAT_INFO1_NUM)
#define BAT2_GROUP_STAT_INFO2_NUM		60

#define BAT2_GROUP_STAT_INFO3_OFFSET	(BAT2_GROUP_STAT_INFO2_OFFSET+BAT2_GROUP_STAT_INFO1_NUM)
#define BAT2_GROUP_STAT_INFO3_NUM		60

#define BAT2_GROUP_STAT_INFO4_OFFSET	(BAT2_GROUP_STAT_INFO3_OFFSET+BAT2_GROUP_STAT_INFO1_NUM)
#define BAT2_GROUP_STAT_INFO4_NUM		60

#define BAT2_GROUP_STAT_INFO5_OFFSET	(BAT2_GROUP_STAT_INFO4_OFFSET+BAT2_GROUP_STAT_INFO1_NUM)
#define BAT2_GROUP_STAT_INFO5_NUM		60

#define BAT2_GROUP_STAT_INFO6_OFFSET	(BAT2_GROUP_STAT_INFO5_OFFSET+BAT2_GROUP_STAT_INFO1_NUM)
#define BAT2_GROUP_STAT_INFO6_NUM		60

#define BAT2_GROUP_STAT_INFO7_OFFSET	(BAT2_GROUP_STAT_INFO6_OFFSET+BAT2_GROUP_STAT_INFO1_NUM)
#define BAT2_GROUP_STAT_INFO7_NUM		60

#define BAT2_GROUP_STAT_INFO8_OFFSET	(BAT2_GROUP_STAT_INFO7_OFFSET+BAT2_GROUP_STAT_INFO1_NUM)
#define BAT2_GROUP_STAT_INFO8_NUM		60

#define BAT2_GROUP_STAT_INFO9_OFFSET	(BAT2_GROUP_STAT_INFO8_OFFSET+BAT2_GROUP_STAT_INFO1_NUM)
#define BAT2_GROUP_STAT_INFO9_NUM		60

#define BAT2_GROUP_STAT_INFO10_OFFSET	(BAT2_GROUP_STAT_INFO9_OFFSET+BAT2_GROUP_STAT_INFO1_NUM)
#define BAT2_GROUP_STAT_INFO10_NUM		60
/***********************************巡检模块测量时间间隔存储地址********************************************/
#define BAT_TEST_TIME_PERIOD_OFFSET	(BAT2_GROUP_STAT_INFO10_OFFSET+BAT2_GROUP_STAT_INFO10_NUM)
#define BAT_TEST_TIME_PERIOD_NUM		50

#define BAT1_TEST_TIME_PERIOD_OFFSET	(BAT2_GROUP_STAT_INFO10_OFFSET+BAT2_GROUP_STAT_INFO10_NUM)//暂时没用
#define BAT1_TEST_TIME_PERIOD_NUM		2

#define BAT2_TEST_TIME_PERIOD_OFFSET	(BAT1_TEST_TIME_PERIOD_OFFSET+BAT1_TEST_TIME_PERIOD_NUM)//暂时没用
#define BAT2_TEST_TIME_PERIOD_NUM		2
/***********************************放电仪数据存储地址****************************/
//放电数据标识存储位置，1表示有测试报告，0表示没有
#define FDY_DISC_FLAG1_OFFSET	(BAT_TEST_TIME_PERIOD_OFFSET+BAT_TEST_TIME_PERIOD_NUM)
#define FDY_DISC_FLAG1_NUM		1
//放电参数数据
#define FDY_PARA_SAVE_OFFSET	(FDY_DISC_FLAG1_OFFSET+FDY_DISC_FLAG1_NUM)
#define FDY_PARA_SAVE_NUM		14
//放电时刻的参数存储地址
#define FDY_DISC_PARA_SAVE_OFFSET	(FDY_PARA_SAVE_OFFSET+FDY_PARA_SAVE_NUM)
#define FDY_DISC_PARA_SAVE_NUM		14//字节数，不是寄存器数
//放电起始时间存储地址
#define FDY_DISC_TIME_SAVE1_OFFSET	(FDY_DISC_PARA_SAVE_OFFSET+FDY_DISC_PARA_SAVE_NUM)
#define FDY_DISC_TIME_SAVE1_NUM		12
//放电前电池组组电压存储地址
#define FDY_GROUPV_SAVE1_OFFSET	(FDY_DISC_TIME_SAVE1_OFFSET+FDY_DISC_TIME_SAVE1_NUM)
#define FDY_GROUPV_SAVE1_NUM		2
//放电前电池组环境温度存储地址
#define FDY_ENVIR_TEMP_SAVE1_OFFSET	(FDY_GROUPV_SAVE1_OFFSET+FDY_GROUPV_SAVE1_NUM)
#define FDY_ENVIR_TEMP_SAVE1_NUM		4
//放电前电池数据存储地址
#define FDY_DISC_DATAV_SAVE1_OFFSET	(FDY_ENVIR_TEMP_SAVE1_OFFSET+FDY_ENVIR_TEMP_SAVE1_NUM)
#define FDY_DISC_DATAV_SAVE1_NUM		480
//放电前电池数据存储地址
#define FDY_DISC_DATAT_SAVE1_OFFSET	(FDY_DISC_DATAV_SAVE1_OFFSET+FDY_DISC_DATAV_SAVE1_NUM)
#define FDY_DISC_DATAT_SAVE1_NUM		960
//放电数据标识存储位置，1表示有测试报告，0表示没有
#define FDY_DISC_FLAG2_OFFSET	(FDY_DISC_DATAT_SAVE1_OFFSET+FDY_DISC_DATAT_SAVE1_NUM)
#define FDY_DISC_FLAG2_NUM		1
//放电结束时间存储地址
#define FDY_DISC_TIME_SAVE2_OFFSET	(FDY_DISC_FLAG2_OFFSET+FDY_DISC_FLAG2_NUM)
#define FDY_DISC_TIME_SAVE2_NUM		12
//放电结束电池组组电压存储地址
#define FDY_GROUPV_SAVE2_OFFSET	(FDY_DISC_TIME_SAVE2_OFFSET+FDY_DISC_TIME_SAVE2_NUM)
#define FDY_GROUPV_SAVE2_NUM		2
//放电结束电池组环境温度存储地址
#define FDY_ENVIR_TEMP_SAVE2_OFFSET	(FDY_GROUPV_SAVE2_OFFSET+FDY_GROUPV_SAVE2_NUM)
#define FDY_ENVIR_TEMP_SAVE2_NUM		4
//放电后电池数据存储地址
#define FDY_DISC_DATAV_SAVE2_OFFSET	(FDY_ENVIR_TEMP_SAVE2_OFFSET+FDY_ENVIR_TEMP_SAVE2_NUM)
#define FDY_DISC_DATAV_SAVE2_NUM		480
//放电结束电池数据存储地址
#define FDY_DISC_DATAT_SAVE2_OFFSET	(FDY_DISC_DATAV_SAVE2_OFFSET+FDY_DISC_DATAV_SAVE2_NUM)
#define FDY_DISC_DATAT_SAVE2_NUM		960
//放电结束容量数据存储地址
#define FDY_DISC_CAPACITY_SAVE_OFFSET	(FDY_DISC_DATAT_SAVE2_OFFSET+FDY_DISC_DATAT_SAVE2_NUM)
#define FDY_DISC_CAPACITY_SAVE_NUM		4
//放电停止原因存储地址
#define FDY_DISC_OVER_REASON_OFFSET	(FDY_DISC_CAPACITY_SAVE_OFFSET+FDY_DISC_CAPACITY_SAVE_NUM)
#define FDY_DISC_OVER_REASON_NUM		1
/****************************电池SOC、SOH存储地址***********************************/
//SOC存储地址
#define SOC_SAVE1_OFFSET	(FDY_DISC_OVER_REASON_OFFSET+FDY_DISC_OVER_REASON_NUM)
#define SOC_SAVE1_NUM		4
#define SOC_SAVE2_OFFSET	(SOC_SAVE1_OFFSET+SOC_SAVE1_NUM)
#define SOC_SAVE2_NUM		4

//SOH存储地址
#define SOH_SAVE1_OFFSET	(SOC_SAVE2_OFFSET+SOC_SAVE2_NUM)
#define SOH_SAVE1_NUM		4
#define SOH_SAVE2_OFFSET	(SOH_SAVE1_OFFSET+SOH_SAVE1_NUM)
#define SOH_SAVE2_NUM		4

/****************************实时电压存储地址***********************************/
//实时电压存储参数:实时电压最近一次存储位置，总共存储了多少次
//非充放电状态时默认1小时保存一次数据，充放电状态时2分钟保存一次数据
#define SAVE_TOTAL_TIMES	60//总共存储360次，360次循环存储
#define SAVE1_TIME_PERIOD_ADDR_OFFSET	(SOH_SAVE2_OFFSET+SOH_SAVE2_NUM)
#define SAVE1_TIME_PERIOD_ADDR_NUM	2//保存实时数据的时间间隔，以小时为单位
#define SAVE2_TIME_PERIOD_ADDR_OFFSET	(SAVE1_TIME_PERIOD_ADDR_OFFSET+SAVE1_TIME_PERIOD_ADDR_NUM)
#define SAVE2_TIME_PERIOD_ADDR_NUM	2//保存实时数据的时间间隔，以小时为单位

#define G1_SAVE_ADDR_OFFSET	(SAVE2_TIME_PERIOD_ADDR_OFFSET+SAVE2_TIME_PERIOD_ADDR_NUM)
#define G1_SAVE_ADDR_NUM		2
#define G1_SAVE_TOTAL_TIME_OFFSET	(G1_SAVE_ADDR_OFFSET+G1_SAVE_ADDR_NUM)
#define G1_SAVE_TOTAL_TIME_NUM		2
//第二组存储数据的参数
#define G2_SAVE_ADDR_OFFSET	(G1_SAVE_TOTAL_TIME_OFFSET+G1_SAVE_TOTAL_TIME_NUM)
#define G2_SAVE_ADDR_NUM		2
#define G2_SAVE_TOTAL_TIME_OFFSET	(G2_SAVE_ADDR_OFFSET+G2_SAVE_ADDR_NUM)
#define G2_SAVE_TOTAL_TIME_NUM		2
//每次存储数据的时间
#define G1_SAVE_TIME_OFFSET	(G2_SAVE_TOTAL_TIME_OFFSET+G2_SAVE_TOTAL_TIME_NUM)
#define G1_SAVE_TIME_NUM	12
//组电压存储
#define GV_G1_SAVE_ADDR_OFFSET	(G1_SAVE_TIME_OFFSET+G1_SAVE_TIME_NUM*SAVE_TOTAL_TIMES)
#define GV_G1_SAVE_ADDR_NUM	4
//充放电电流存储
#define I_G1_SAVE_ADDR_OFFSET	(GV_G1_SAVE_ADDR_OFFSET+GV_G1_SAVE_ADDR_NUM*SAVE_TOTAL_TIMES)
#define I_G1_SAVE_ADDR_NUM	4
//实时电压存储,最多只存120节电池的电池电压数据
#define V_G1_SAVE_ADDR_TIMES1_OFFSET (I_G1_SAVE_ADDR_OFFSET+I_G1_SAVE_ADDR_NUM*SAVE_TOTAL_TIMES)
#define V_G1_SAVE_ADDR_TIMES_NUM		240
#define G2_SAVE_TIME_OFFSET	(V_G1_SAVE_ADDR_TIMES1_OFFSET+V_G1_SAVE_ADDR_TIMES_NUM*SAVE_TOTAL_TIMES)
#define G2_SAVE_TIME_NUM	12
#define GV_G2_SAVE_ADDR_OFFSET	(G2_SAVE_TIME_OFFSET+G2_SAVE_TIME_NUM*SAVE_TOTAL_TIMES)
#define GV_G2_SAVE_ADDR_NUM	4
#define I_G2_SAVE_ADDR_OFFSET	(GV_G2_SAVE_ADDR_OFFSET+GV_G2_SAVE_ADDR_NUM*SAVE_TOTAL_TIMES)
#define I_G2_SAVE_ADDR_NUM	4
//第二组实时电压
#define V_G2_SAVE_ADDR_TIMES1_OFFSET (I_G2_SAVE_ADDR_OFFSET+I_G2_SAVE_ADDR_NUM*SAVE_TOTAL_TIMES)
#define V_G2_SAVE_ADDR_TIMES_NUM		240

//暂时不存实时单体温度
////第一组实时温度
//#define T_G1_SAVE_ADDR_TIMES1_OFFSET (V_G2_SAVE_ADDR_TIMES1_OFFSET+V_G2_SAVE_ADDR_TIMES_NUM*SAVE_TOTAL_TIMES)
//#define T_G1_SAVE_ADDR_TIMES_NUM		960
////第二组实时温度
//#define T_G2_SAVE_ADDR_TIMES1_OFFSET (T_G1_SAVE_ADDR_TIMES1_OFFSET+T_G1_SAVE_ADDR_TIMES_NUM*SAVE_TOTAL_TIMES)
//#define T_G2_SAVE_ADDR_TIMES_NUM		960
/************************放电实时数据时间间隔存储地址******************/

/****************************放电实时电压存储地址***********************************/
//放电实时电压存储参数:实时电压最近一次存储位置，总共存储了多少次
//非充放电状态时默认1小时保存一次数据，充放电状态时2分钟保存一次数据
#define DISC_DATA_SAVE_TOTAL_TIMES	60//总共存储360次，360次循环存储
#define DISC1_SAVE_TIME_PERIOD_OFFSET	(V_G2_SAVE_ADDR_TIMES1_OFFSET+V_G2_SAVE_ADDR_TIMES_NUM*SAVE_TOTAL_TIMES)
#define DISC1_SAVE_TIME_PERIOD_NUM		4
#define DISC2_SAVE_TIME_PERIOD_OFFSET	(DISC1_SAVE_TIME_PERIOD_OFFSET+DISC1_SAVE_TIME_PERIOD_NUM)
#define DISC2_SAVE_TIME_PERIOD_NUM		4

#define G1_DISC_DATA_ADDR_OFFSET	(DISC2_SAVE_TIME_PERIOD_OFFSET+DISC2_SAVE_TIME_PERIOD_NUM)
#define G1_DISC_DATA_ADDR_NUM		2
#define G1_DISC_DATA_TOTAL_TIME_OFFSET	(G1_DISC_DATA_ADDR_OFFSET+G1_DISC_DATA_ADDR_NUM)
#define G1_DISC_DATA_TOTAL_TIME_NUM		2
//每次存储数据的时间
#define G1_DISC_DATA_TIME_OFFSET	(G1_DISC_DATA_TOTAL_TIME_OFFSET+G1_DISC_DATA_TOTAL_TIME_NUM)
#define G1_DISC_DATA_TIME_NUM		12
//组电压存储
#define GV_G1_DISC_DATA_ADDR_OFFSET	(G1_DISC_DATA_TIME_OFFSET+G1_DISC_DATA_TIME_NUM*DISC_DATA_SAVE_TOTAL_TIMES)
#define GV_G1_DISC_DATA_ADDR_NUM		4
//充放电电流存储
#define I_G1_DISC_DATA_ADDR_OFFSET	(GV_G1_DISC_DATA_ADDR_OFFSET+GV_G1_DISC_DATA_ADDR_NUM*DISC_DATA_SAVE_TOTAL_TIMES)
#define I_G1_DISC_DATA_ADDR_NUM		4
//实时电压存储,最多只存120节电池的电池电压数据
#define V_G1_DISC_DATA_ADDR_TIMES1_OFFSET (I_G1_DISC_DATA_ADDR_OFFSET+I_G1_DISC_DATA_ADDR_NUM*DISC_DATA_SAVE_TOTAL_TIMES)
#define V_G1_DISC_DATA_ADDR_TIMES_NUM		240

#define G2_DISC_DATA_ADDR_OFFSET	(V_G1_DISC_DATA_ADDR_TIMES1_OFFSET+V_G1_DISC_DATA_ADDR_TIMES_NUM*DISC_DATA_SAVE_TOTAL_TIMES)
#define G2_DISC_DATA_ADDR_NUM		2
#define G2_DISC_DATA_TOTAL_TIME_OFFSET	(G2_DISC_DATA_ADDR_OFFSET+G2_DISC_DATA_ADDR_NUM)
#define G2_DISC_DATA_TOTAL_TIME_NUM		2
//每次存储数据的时间
#define G2_DISC_DATA_TIME_OFFSET	(G2_DISC_DATA_TOTAL_TIME_OFFSET+G2_DISC_DATA_TOTAL_TIME_NUM)
#define G2_DISC_DATA_TIME_NUM		12
//组电压存储
#define GV_G2_DISC_DATA_ADDR_OFFSET	(G2_DISC_DATA_TIME_OFFSET+G2_DISC_DATA_TIME_NUM*DISC_DATA_SAVE_TOTAL_TIMES)
#define GV_G2_DISC_DATA_ADDR_NUM		4
//充放电电流存储
#define I_G2_DISC_DATA_ADDR_OFFSET	(GV_G2_DISC_DATA_ADDR_OFFSET+GV_G2_DISC_DATA_ADDR_NUM*DISC_DATA_SAVE_TOTAL_TIMES)
#define I_G2_DISC_DATA_ADDR_NUM		4
//实时电压存储,最多只存120节电池的电池电压数据
#define V_G2_DISC_DATA_ADDR_TIMES1_OFFSET (I_G2_DISC_DATA_ADDR_OFFSET+I_G2_DISC_DATA_ADDR_NUM*DISC_DATA_SAVE_TOTAL_TIMES)
#define V_G2_DISC_DATA_ADDR_TIMES_NUM		240

/****************************屏蔽数据存储地址***********************************/
//电池电压屏蔽
#define BAT1_V_SHIELD_ADDR_OFFSET (V_G2_DISC_DATA_ADDR_TIMES1_OFFSET+V_G2_DISC_DATA_ADDR_TIMES_NUM*DISC_DATA_SAVE_TOTAL_TIMES)
#define BAT1_V_SINGAL_SHIELD_ADDR_NUM	 14
#define BAT1_V_SHIELD_ADDR_NUM	 BAT1_V_SINGAL_SHIELD_ADDR_NUM*BAT_V_SHIELD_SUM
#define BAT2_V_SHIELD_ADDR_OFFSET (BAT1_V_SHIELD_ADDR_OFFSET+BAT1_V_SHIELD_ADDR_NUM)
#define BAT2_V_SINGAL_SHIELD_ADDR_NUM	 14
#define BAT2_V_SHIELD_ADDR_NUM	 BAT2_V_SINGAL_SHIELD_ADDR_NUM*BAT_V_SHIELD_SUM
//电池温度屏蔽
#define TEMP1_SHIELD_ADDR_OFFSET (BAT2_V_SHIELD_ADDR_OFFSET + BAT2_V_SHIELD_ADDR_NUM)
#define TEMP1_SHIELD_ADDR_NUM	MAX_DEV_NUM*2*2//一个模块需要四个字节的屏蔽信息
#define TEMP2_SHIELD_ADDR_OFFSET (TEMP1_SHIELD_ADDR_OFFSET + TEMP1_SHIELD_ADDR_NUM)
#define TEMP2_SHIELD_ADDR_NUM	MAX_DEV_NUM*2*2//一个模块需要四个字节的屏蔽信息







/****************************历史记录段存储地址***********************************/

void InitDataI2c(void);
uint8 BatVDataSave(uint8 groupnum,uint8 DevAddr,uint8 TimesFlag);
uint8 BatStatDataSave(uint8 batgroup,uint8 TimesFlag);
uint8 BatTempDataSave(uint8 groupnum,uint8 DevAddr,uint8 TimesFlag);
uint8 InnerRDataSave(uint8 groupnum,uint8 DevAddr);
uint8 CRDataSave(uint8 groupnum,uint8 DevAddr);
uint8 HistoryDataSave(uint8 batgroup,uint8 DevAddr,uint8 ErrSource,uint8 ErrType,int16 ErrData);
void ResetFactoryPara(void);
void InitSysCFG(void);
void InitComPurpose(void);
void InitComPara(void);
void BatTestDataSave(uint8 batgroup);
void BatTestVTSave(uint8 batgroup);
void TestTimePeriodSave(void);
void TestTimePeriodRead(void);
void FdyPreDiscDataSave(uint8 batgroup);
void FdyAfterDiscDataSave(uint8 batgroup);
uint8 BatDataSave(uint8 batgroup);
void DiscDataPeriodSave(void);
uint8 DiscBatDataSave(uint8 batgroup);



#endif



